QUESTIONS = [
    # ── Height Questions ──
    {
        "category": "Famous Buildings",
        "question": "How tall is the Burj Khalifa in Dubai, the world's tallest building?",
        "choices": ["1,776 ft", "2,717 ft", "2,073 ft", "1,972 ft"],
        "answer": "2,717 ft",
    },
    {
        "category": "Famous Buildings",
        "question": "How tall is the Empire State Building (to the roof, not antenna)?",
        "choices": ["1,050 ft", "1,250 ft", "1,454 ft", "980 ft"],
        "answer": "1,250 ft",
    },
    {
        "category": "Famous Buildings",
        "question": "How tall is the Eiffel Tower including the antenna?",
        "choices": ["984 ft", "1,083 ft", "1,210 ft", "886 ft"],
        "answer": "1,083 ft",
    },
    {
        "category": "Famous Buildings",
        "question": "Which of these is the tallest?",
        "choices": ["Willis Tower (Chicago)", "Taipei 101", "Shanghai Tower", "One World Trade Center"],
        "answer": "Shanghai Tower",
    },
    {
        "category": "Famous Buildings",
        "question": "How tall is the Great Pyramid of Giza at its original height?",
        "choices": ["321 ft", "481 ft", "590 ft", "410 ft"],
        "answer": "481 ft",
    },
    {
        "category": "Famous Buildings",
        "question": "The Leaning Tower of Pisa is approximately how tall on its low side?",
        "choices": ["115 ft", "144 ft", "183 ft", "210 ft"],
        "answer": "183 ft",
    },
    {
        "category": "Famous Buildings",
        "question": "How tall is Big Ben's clock tower (Elizabeth Tower) in London?",
        "choices": ["250 ft", "316 ft", "365 ft", "290 ft"],
        "answer": "316 ft",
    },
    {
        "category": "Famous Buildings",
        "question": "The CN Tower in Toronto held the world's tallest free-standing structure record until 2007. How tall is it?",
        "choices": ["1,815 ft", "1,500 ft", "1,670 ft", "2,000 ft"],
        "answer": "1,815 ft",
    },
    # ── Construction Date Questions ──
    {
        "category": "Famous Buildings",
        "question": "In what year was the Colosseum in Rome completed?",
        "choices": ["50 AD", "80 AD", "120 AD", "200 AD"],
        "answer": "80 AD",
    },
    {
        "category": "Famous Buildings",
        "question": "When was the Taj Mahal completed?",
        "choices": ["1553", "1607", "1653", "1701"],
        "answer": "1653",
    },
    {
        "category": "Famous Buildings",
        "question": "When was the Empire State Building completed?",
        "choices": ["1929", "1931", "1935", "1927"],
        "answer": "1931",
    },
    {
        "category": "Famous Buildings",
        "question": "When did the Eiffel Tower open to the public?",
        "choices": ["1875", "1889", "1893", "1901"],
        "answer": "1889",
    },
    {
        "category": "Famous Buildings",
        "question": "When was the Sydney Opera House officially opened?",
        "choices": ["1959", "1965", "1973", "1980"],
        "answer": "1973",
    },
    {
        "category": "Famous Buildings",
        "question": "Construction of the Sagrada Familia in Barcelona began in what year?",
        "choices": ["1852", "1882", "1905", "1920"],
        "answer": "1882",
    },
    {
        "category": "Famous Buildings",
        "question": "When was the Parthenon in Athens originally completed?",
        "choices": ["438 BC", "300 BC", "510 BC", "200 BC"],
        "answer": "438 BC",
    },
    {
        "category": "Famous Buildings",
        "question": "When was the Burj Khalifa officially opened?",
        "choices": ["2006", "2008", "2010", "2012"],
        "answer": "2010",
    },
    {
        "category": "Famous Buildings",
        "question": "The original World Trade Center Twin Towers were completed in what year?",
        "choices": ["1968", "1971", "1973", "1976"],
        "answer": "1973",
    },
    {
        "category": "Famous Buildings",
        "question": "When was the Pentagon completed?",
        "choices": ["1937", "1943", "1948", "1952"],
        "answer": "1943",
    },
    # ── Size & Facts Questions ──
    {
        "category": "Famous Buildings",
        "question": "How many floors does the Burj Khalifa have?",
        "choices": ["130", "148", "163", "175"],
        "answer": "163",
    },
    {
        "category": "Famous Buildings",
        "question": "The Pentagon is the world's largest office building by floor area. How many sides does it have?",
        "choices": ["4", "5", "6", "8"],
        "answer": "5",
    },
    {
        "category": "Famous Buildings",
        "question": "How many stones make up the Great Pyramid of Giza (approximately)?",
        "choices": ["500,000", "1.2 million", "2.3 million", "5 million"],
        "answer": "2.3 million",
    },
    {
        "category": "Famous Buildings",
        "question": "What is the approximate floor area of the Palace of Versailles?",
        "choices": ["250,000 sq ft", "721,000 sq ft", "1.2 million sq ft", "500,000 sq ft"],
        "answer": "721,000 sq ft",
    },
    {
        "category": "Famous Buildings",
        "question": "How many rooms does Buckingham Palace have?",
        "choices": ["365", "520", "775", "1,000"],
        "answer": "775",
    },
    {
        "category": "Famous Buildings",
        "question": "The Colosseum in Rome could hold approximately how many spectators?",
        "choices": ["25,000", "50,000", "80,000", "120,000"],
        "answer": "50,000",
    },
    {
        "category": "Famous Buildings",
        "question": "How long is the Great Wall of China?",
        "choices": ["5,500 miles", "8,000 miles", "13,171 miles", "18,000 miles"],
        "answer": "13,171 miles",
    },
    {
        "category": "Famous Buildings",
        "question": "How many windows does the Empire State Building have?",
        "choices": ["3,400", "6,514", "8,200", "10,000"],
        "answer": "6,514",
    },
    # ── Location & General Knowledge ──
    {
        "category": "Famous Buildings",
        "question": "In which country is the Petronas Towers located?",
        "choices": ["Indonesia", "Malaysia", "Singapore", "Thailand"],
        "answer": "Malaysia",
    },
    {
        "category": "Famous Buildings",
        "question": "What material gives the Taj Mahal its white appearance?",
        "choices": ["Limestone", "White marble", "Granite", "Alabaster"],
        "answer": "White marble",
    },
    {
        "category": "Famous Buildings",
        "question": "Who designed the Guggenheim Museum in New York City?",
        "choices": ["I.M. Pei", "Frank Lloyd Wright", "Le Corbusier", "Frank Gehry"],
        "answer": "Frank Lloyd Wright",
    },
    {
        "category": "Famous Buildings",
        "question": "What famous architect designed the Sydney Opera House?",
        "choices": ["Renzo Piano", "Jorn Utzon", "Zaha Hadid", "Norman Foster"],
        "answer": "Jorn Utzon",
    },
    {
        "category": "Famous Buildings",
        "question": "What is the Leaning Tower of Pisa's tilt caused by?",
        "choices": ["Earthquake damage", "Soft ground on one side", "Intentional design", "Wind erosion"],
        "answer": "Soft ground on one side",
    },
    {
        "category": "Famous Buildings",
        "question": "Which building was the world's tallest from 1931 to 1970?",
        "choices": ["Chrysler Building", "Empire State Building", "Willis Tower", "30 Rock"],
        "answer": "Empire State Building",
    },
    {
        "category": "Famous Buildings",
        "question": "The Forbidden City in Beijing has approximately how many rooms?",
        "choices": ["2,500", "5,000", "8,700", "12,000"],
        "answer": "8,700",
    },
    {
        "category": "Famous Buildings",
        "question": "What ancient wonder was located in the city of Babylon?",
        "choices": ["Colossus of Rhodes", "Hanging Gardens", "Lighthouse of Alexandria", "Temple of Artemis"],
        "answer": "Hanging Gardens",
    },
    # ── Picture Questions (Emoji) ──
    {
        "category": "Famous Buildings",
        "question": "Which famous landmark is this?",
        "image": {"type": "emoji", "content": "\U0001F5FC"},
        "choices": ["Eiffel Tower", "Tokyo Tower", "CN Tower", "Berlin TV Tower"],
        "answer": "Tokyo Tower",
    },
    {
        "category": "Famous Buildings",
        "question": "Which famous landmark is this?",
        "image": {"type": "emoji", "content": "\U0001F5FD"},
        "choices": ["Christ the Redeemer", "Statue of Liberty", "Colossus of Rhodes", "Angel of the North"],
        "answer": "Statue of Liberty",
    },
    {
        "category": "Famous Buildings",
        "question": "Which type of building is this?",
        "image": {"type": "emoji", "content": "\U0001F3F0"},
        "choices": ["Palace", "Castle", "Cathedral", "Fortress"],
        "answer": "Castle",
    },
    {
        "category": "Famous Buildings",
        "question": "Which type of structure is this?",
        "image": {"type": "emoji", "content": "\U0001F3DB\uFE0F"},
        "choices": ["Colosseum", "Classical Temple", "Amphitheater", "Aqueduct"],
        "answer": "Classical Temple",
    },
    # ── Picture Questions (URL - Wikimedia Commons) ──
    {
        "category": "Famous Buildings",
        "question": "Identify this famous building:",
        "image": {"type": "url", "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Empire_State_Building_%28aerial_view%29.jpg/300px-Empire_State_Building_%28aerial_view%29.jpg", "alt": "A famous skyscraper"},
        "choices": ["Chrysler Building", "Empire State Building", "One World Trade Center", "30 Rockefeller Plaza"],
        "answer": "Empire State Building",
    },
    {
        "category": "Famous Buildings",
        "question": "Identify this famous structure:",
        "image": {"type": "url", "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Sydney_Australia._%2821339175489%29.jpg/300px-Sydney_Australia._%2821339175489%29.jpg", "alt": "A famous building"},
        "choices": ["Walt Disney Concert Hall", "Sydney Opera House", "Guggenheim Bilbao", "Beijing National Stadium"],
        "answer": "Sydney Opera House",
    },
    {
        "category": "Famous Buildings",
        "question": "Identify this famous landmark:",
        "image": {"type": "url", "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image-Colosseum_in_Rome%2C_Italy_-_April_2007.jpg/300px-Image-Colosseum_in_Rome%2C_Italy_-_April_2007.jpg", "alt": "An ancient structure"},
        "choices": ["Parthenon", "Roman Forum", "Colosseum", "Pantheon"],
        "answer": "Colosseum",
    },
    {
        "category": "Famous Buildings",
        "question": "Identify this famous building:",
        "image": {"type": "url", "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Taj_Mahal_in_March_2004.jpg/300px-Taj_Mahal_in_March_2004.jpg", "alt": "A famous white building"},
        "choices": ["White House", "Taj Mahal", "Palace of Versailles", "Sheikh Zayed Mosque"],
        "answer": "Taj Mahal",
    },
    {
        "category": "Famous Buildings",
        "question": "Identify this famous tower:",
        "image": {"type": "url", "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg/188px-Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg", "alt": "A famous tower"},
        "choices": ["Tokyo Tower", "Blackpool Tower", "Eiffel Tower", "CN Tower"],
        "answer": "Eiffel Tower",
    },
    {
        "category": "Famous Buildings",
        "question": "Identify this famous structure:",
        "image": {"type": "url", "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Kheops-Pyramid.jpg/300px-Kheops-Pyramid.jpg", "alt": "An ancient structure"},
        "choices": ["Pyramid of Djoser", "Great Pyramid of Giza", "Red Pyramid", "Pyramid of the Sun"],
        "answer": "Great Pyramid of Giza",
    },
    {
        "category": "Famous Buildings",
        "question": "Identify this famous landmark:",
        "image": {"type": "url", "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Leaning_Tower_of_Pisa_%28April_2012%29.jpg/220px-Leaning_Tower_of_Pisa_%28April_2012%29.jpg", "alt": "A famous tower"},
        "choices": ["Campanile di San Marco", "Leaning Tower of Pisa", "Giotto's Bell Tower", "Tower of London"],
        "answer": "Leaning Tower of Pisa",
    },
    {
        "category": "Famous Buildings",
        "question": "Identify this famous building:",
        "image": {"type": "url", "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/All_Gizah_Pyramids.jpg/300px-All_Gizah_Pyramids.jpg", "alt": "Ancient structures in a desert"},
        "choices": ["Pyramids of Meroe", "Pyramids of Giza", "Pyramids of Teotihuacan", "Nubian Pyramids"],
        "answer": "Pyramids of Giza",
    },
]
