QUESTIONS = [
    # ── Deductive Reasoning ──
    {
        "category": "Logic",
        "question": "If all roses are flowers and some flowers fade quickly, can we conclude that some roses fade quickly?",
        "choices": ["Yes", "No", "Only in summer", "Sometimes"],
        "answer": "No",
    },
    {
        "category": "Logic",
        "question": "All cats are animals. All animals need water. What can we conclude?",
        "choices": ["All animals are cats", "All cats need water", "Some cats don't need water", "Water needs cats"],
        "answer": "All cats need water",
    },
    {
        "category": "Logic",
        "question": "If it is raining, the ground is wet. The ground is wet. Can we conclude it is raining?",
        "choices": ["Yes", "No", "Only if there is no sprinkler", "Probably"],
        "answer": "No",
    },
    {
        "category": "Logic",
        "question": "No fish can fly. A tuna is a fish. What follows?",
        "choices": ["A tuna can fly", "A tuna cannot fly", "Some tunas can fly", "Not enough info"],
        "answer": "A tuna cannot fly",
    },
    {
        "category": "Logic",
        "question": "If A > B and B > C, which must be true?",
        "choices": ["C > A", "A > C", "A = C", "B > A"],
        "answer": "A > C",
    },
    {
        "category": "Logic",
        "question": "All Bloops are Razzles. All Razzles are Lazzles. Are all Bloops definitely Lazzles?",
        "choices": ["Yes", "No", "Maybe", "Not enough info"],
        "answer": "Yes",
    },
    {
        "category": "Logic",
        "question": "If no heroes are cowards and some soldiers are cowards, what must be true?",
        "choices": ["All soldiers are heroes", "Some soldiers are not heroes", "No soldiers are heroes", "All heroes are soldiers"],
        "answer": "Some soldiers are not heroes",
    },
    {
        "category": "Logic",
        "question": "If all squares are rectangles, but not all rectangles are squares, which is true?",
        "choices": ["Some rectangles are not squares", "No squares are rectangles", "All rectangles are squares", "Squares don't exist"],
        "answer": "Some rectangles are not squares",
    },
    # ── Pattern & Sequence ──
    {
        "category": "Logic",
        "question": "What comes next: 1, 1, 2, 3, 5, 8, 13, ...?",
        "choices": ["18", "20", "21", "26"],
        "answer": "21",
    },
    {
        "category": "Logic",
        "question": "What comes next: 2, 6, 18, 54, ...?",
        "choices": ["108", "162", "72", "216"],
        "answer": "162",
    },
    {
        "category": "Logic",
        "question": "What comes next: 1, 4, 9, 16, 25, ...?",
        "choices": ["30", "36", "49", "32"],
        "answer": "36",
    },
    {
        "category": "Logic",
        "question": "What comes next: O, T, T, F, F, S, S, ...?",
        "choices": ["E", "N", "T", "O"],
        "answer": "E",
    },
    {
        "category": "Logic",
        "question": "What comes next: 3, 6, 11, 18, 27, ...?",
        "choices": ["36", "38", "34", "40"],
        "answer": "38",
    },
    {
        "category": "Logic",
        "question": "What comes next: Z, Y, X, W, V, ...?",
        "choices": ["S", "T", "U", "R"],
        "answer": "U",
    },
    {
        "category": "Logic",
        "question": "What comes next: 1, 3, 7, 15, 31, ...?",
        "choices": ["47", "55", "62", "63"],
        "answer": "63",
    },
    {
        "category": "Logic",
        "question": "What comes next: 2, 3, 5, 7, 11, 13, ...?",
        "choices": ["15", "17", "19", "14"],
        "answer": "17",
    },
    # ── Classic Riddles & Brain Teasers ──
    {
        "category": "Logic",
        "question": "I have cities but no houses, forests but no trees, and water but no fish. What am I?",
        "choices": ["A dream", "A map", "A painting", "A story"],
        "answer": "A map",
    },
    {
        "category": "Logic",
        "question": "A man has 3 daughters. Each daughter has a brother. How many children does he have?",
        "choices": ["4", "6", "7", "3"],
        "answer": "4",
    },
    {
        "category": "Logic",
        "question": "If you have a bowl with six apples and you take away four, how many do you have?",
        "choices": ["2", "4", "6", "0"],
        "answer": "4",
    },
    {
        "category": "Logic",
        "question": "A farmer has 17 sheep. All but 9 die. How many are left?",
        "choices": ["8", "9", "17", "0"],
        "answer": "9",
    },
    {
        "category": "Logic",
        "question": "How many times can you subtract 5 from 25?",
        "choices": ["5 times", "4 times", "1 time", "25 times"],
        "answer": "1 time",
    },
    {
        "category": "Logic",
        "question": "Two fathers and two sons go fishing. They each catch one fish. They bring home 3 fish. How?",
        "choices": ["One fish escaped", "They are grandfather, father, son", "They shared a fish", "One was thrown back"],
        "answer": "They are grandfather, father, son",
    },
    {
        "category": "Logic",
        "question": "What weighs more: a pound of feathers or a pound of bricks?",
        "choices": ["Feathers", "Bricks", "They weigh the same", "Depends on gravity"],
        "answer": "They weigh the same",
    },
    {
        "category": "Logic",
        "question": "If there are 3 apples and you take away 2, how many apples do YOU have?",
        "choices": ["1", "2", "3", "0"],
        "answer": "2",
    },
    # ── Probability & Counting ──
    {
        "category": "Logic",
        "question": "You flip a fair coin 3 times. What is the probability of getting exactly 2 heads?",
        "choices": ["1/4", "3/8", "1/2", "1/3"],
        "answer": "3/8",
    },
    {
        "category": "Logic",
        "question": "How many handshakes occur if 5 people each shake hands with every other person exactly once?",
        "choices": ["5", "10", "15", "20"],
        "answer": "10",
    },
    {
        "category": "Logic",
        "question": "You have 8 identical-looking balls. One is heavier. Using a balance scale, what is the minimum number of weighings to find it?",
        "choices": ["1", "2", "3", "4"],
        "answer": "2",
    },
    {
        "category": "Logic",
        "question": "In a room of 23 people, what is the approximate probability that two share a birthday?",
        "choices": ["10%", "25%", "50%", "75%"],
        "answer": "50%",
    },
    {
        "category": "Logic",
        "question": "A bat and a ball cost $1.10 together. The bat costs $1.00 more than the ball. How much does the ball cost?",
        "choices": ["$0.10", "$0.05", "$0.15", "$0.01"],
        "answer": "$0.05",
    },
    {
        "category": "Logic",
        "question": "If you pick one card from a standard deck, what is the probability it's a heart?",
        "choices": ["1/2", "1/3", "1/4", "1/13"],
        "answer": "1/4",
    },
    {
        "category": "Logic",
        "question": "You have 2 ropes that each take exactly 1 hour to burn (but burn unevenly). How do you measure 45 minutes?",
        "choices": ["Light one from both ends and the other from one end", "Cut one rope in half", "Light both from one end", "You can't measure 45 min"],
        "answer": "Light one from both ends and the other from one end",
    },
    # ── True or False Logic ──
    {
        "category": "Logic",
        "question": "Statement: 'This statement is false.' What is the logical status of this statement?",
        "choices": ["True", "False", "Paradox", "Unknown"],
        "answer": "Paradox",
    },
    {
        "category": "Logic",
        "question": "If Monday's child is fair of face, and today is 2 days after Saturday, what day is it?",
        "choices": ["Sunday", "Monday", "Tuesday", "Wednesday"],
        "answer": "Monday",
    },
    {
        "category": "Logic",
        "question": "Three switches control three light bulbs in another room. You can only enter the room once. How do you figure out which switch controls which bulb?",
        "choices": ["Turn all on at once", "Turn on 1, wait, turn on 2, then enter", "It's impossible", "Use a mirror"],
        "answer": "Turn on 1, wait, turn on 2, then enter",
    },
    {
        "category": "Logic",
        "question": "If the day before yesterday was Thursday, what day is tomorrow?",
        "choices": ["Friday", "Saturday", "Sunday", "Monday"],
        "answer": "Sunday",
    },
    {
        "category": "Logic",
        "question": "A doctor gives you 3 pills and tells you to take one every 30 minutes. How long until all pills are taken?",
        "choices": ["90 minutes", "60 minutes", "45 minutes", "30 minutes"],
        "answer": "60 minutes",
    },
    {
        "category": "Logic",
        "question": "You're in a race and you pass the person in 2nd place. What place are you in now?",
        "choices": ["1st", "2nd", "3rd", "It depends"],
        "answer": "2nd",
    },
    {
        "category": "Logic",
        "question": "A windowless room has 3 light bulbs. Outside are 3 switches. You may enter the room only once. How can you determine which switch controls which bulb using heat?",
        "choices": ["Turn on all switches", "Turn on switch 1 for 10 min, off, turn on switch 2, enter", "Flip switches randomly", "Impossible without help"],
        "answer": "Turn on switch 1 for 10 min, off, turn on switch 2, enter",
    },
    {
        "category": "Logic",
        "question": "If you rearrange the letters 'CIFAIPC', you get the name of a(n):",
        "choices": ["Country", "Ocean", "Animal", "City"],
        "answer": "Ocean",
    },
    # ── Mathematical Logic ──
    {
        "category": "Logic",
        "question": "If 5 machines take 5 minutes to make 5 widgets, how long would 100 machines take to make 100 widgets?",
        "choices": ["100 minutes", "5 minutes", "20 minutes", "50 minutes"],
        "answer": "5 minutes",
    },
    {
        "category": "Logic",
        "question": "A lily pad doubles in size every day. If it takes 48 days to fill a lake, how many days to fill half the lake?",
        "choices": ["24 days", "36 days", "47 days", "46 days"],
        "answer": "47 days",
    },
    {
        "category": "Logic",
        "question": "If you have 12 fish, half drown, a quarter swim away, and a third come back, how many do you have?",
        "choices": ["4", "7", "12", "0"],
        "answer": "12",
    },
    {
        "category": "Logic",
        "question": "What is the smallest number of moves needed to solve the Tower of Hanoi with 3 discs?",
        "choices": ["5", "6", "7", "8"],
        "answer": "7",
    },
]
