QUESTIONS = [
    # ── Cooley Surname: Origin & Meaning ──
    {
        "category": "Cooley History",
        "question": "What is the primary language of origin for the Cooley surname?",
        "choices": ["French", "German", "English", "Spanish"],
        "answer": "English",
    },
    {
        "category": "Cooley History",
        "question": "The English form of the Cooley surname derives from the Old English word 'colig'. What does 'colig' mean?",
        "choices": ["Brave or courageous", "Dark or black", "Tall or strong", "Wealthy or noble"],
        "answer": "Dark or black",
    },
    {
        "category": "Cooley History",
        "question": "The Old English root 'col', which contributed to the Cooley surname, is related to which substance?",
        "choices": ["Coal or charcoal", "Gold", "Iron", "Clay"],
        "answer": "Coal or charcoal",
    },
    {
        "category": "Cooley History",
        "question": "In Ireland, the Cooley surname in Galway and Clare is an Anglicized form of which Gaelic name?",
        "choices": ["Mac Giolla Chuille", "O'Sullivan", "Mac Carthaigh", "O'Brien"],
        "answer": "Mac Giolla Chuille",
    },
    {
        "category": "Cooley History",
        "question": "Which of these is NOT a common spelling variant of the Cooley surname?",
        "choices": ["Colley", "Cowley", "Coley", "Crawley"],
        "answer": "Crawley",
    },
    # ── Benjamin Cooley & Early Settlers ──
    {
        "category": "Cooley History",
        "question": "Benjamin Cooley, one of the earliest American Cooleys, settled in which Massachusetts town?",
        "choices": ["Boston", "Plymouth", "Springfield", "Salem"],
        "answer": "Springfield",
    },
    {
        "category": "Cooley History",
        "question": "Benjamin Cooley is believed to have been baptized in Tring, in which English county?",
        "choices": ["Kent", "Hertfordshire", "Yorkshire", "Devon"],
        "answer": "Hertfordshire",
    },
    {
        "category": "Cooley History",
        "question": "Benjamin Cooley held which military title in colonial Massachusetts?",
        "choices": ["Captain", "Colonel", "Ensign", "Sergeant"],
        "answer": "Ensign",
    },
    {
        "category": "Cooley History",
        "question": "Besides Springfield, Benjamin Cooley is also closely associated with which nearby Massachusetts town?",
        "choices": ["Longmeadow", "Northampton", "Cambridge", "Concord"],
        "answer": "Longmeadow",
    },
    {
        "category": "Cooley History",
        "question": "The comprehensive 'Cooley Genealogy' covering Benjamin Cooley's descendants was compiled by which author?",
        "choices": ["Benjamin Franklin Cooley", "Mortimer Elwyn Cooley", "Thomas McIntyre Cooley", "John Adams Cooley"],
        "answer": "Mortimer Elwyn Cooley",
    },
    # ── Benjamin Cooley: Life & Legacy ──
    {
        "category": "Cooley History",
        "question": "What was Benjamin Cooley's trade or occupation in colonial Springfield?",
        "choices": ["Blacksmith", "Weaver", "Carpenter", "Tanner"],
        "answer": "Weaver",
    },
    {
        "category": "Cooley History",
        "question": "How many children did Benjamin and Sarah Cooley have?",
        "choices": ["Five", "Six", "Eight", "Twelve"],
        "answer": "Eight",
    },
    {
        "category": "Cooley History",
        "question": "What was the name of Benjamin Cooley's eldest child, born September 16, 1643?",
        "choices": ["Sarah", "Mary", "Bethia", "Obadiah"],
        "answer": "Bethia",
    },
    {
        "category": "Cooley History",
        "question": "How many times was Benjamin Cooley chosen as Selectman of Springfield?",
        "choices": ["5 times", "10 times", "18 times", "25 times"],
        "answer": "18 times",
    },
    {
        "category": "Cooley History",
        "question": "In what year was Benjamin Cooley first elected Selectman of Springfield?",
        "choices": ["1643", "1646", "1650", "1660"],
        "answer": "1646",
    },
    {
        "category": "Cooley History",
        "question": "In 1650, who was apprenticed to Benjamin Cooley to learn linen weaving?",
        "choices": ["George Colton", "John Pynchon", "Samuel Terry", "Miles Morgan"],
        "answer": "Samuel Terry",
    },
    {
        "category": "Cooley History",
        "question": "Benjamin Cooley was a witness in the 1651 witch trial of which Springfield couple, predating Salem by over 40 years?",
        "choices": ["Hugh and Mary Parsons", "John and Elizabeth Proctor", "Thomas and Ann Putnam", "Samuel and Sarah Good"],
        "answer": "Hugh and Mary Parsons",
    },
    {
        "category": "Cooley History",
        "question": "In 1679, what reason did Benjamin Cooley give when petitioning to resign his Ensign commission?",
        "choices": ["Injury from battle", "Being aged and deaf", "Moving to a new town", "Financial hardship"],
        "answer": "Being aged and deaf",
    },
    {
        "category": "Cooley History",
        "question": "How many days after Benjamin Cooley's death on August 17, 1684 did his wife Sarah die?",
        "choices": ["Two days", "Six days", "Fourteen days", "Thirty days"],
        "answer": "Six days",
    },
    {
        "category": "Cooley History",
        "question": "Approximately how many acres did Benjamin Cooley's estate include at the time of his death?",
        "choices": ["40 acres", "150 acres", "524 acres", "1,000 acres"],
        "answer": "524 acres",
    },
    {
        "category": "Cooley History",
        "question": "During King Philip's War in October 1675, how many of Springfield's 60 houses were burned by attacking forces?",
        "choices": ["10", "25", "45", "58"],
        "answer": "45",
    },
    {
        "category": "Cooley History",
        "question": "How was Benjamin Cooley's surname spelled in the Tring parish baptism records?",
        "choices": ["Cooley", "Coley", "Cowley", "Coulley"],
        "answer": "Coley",
    },
    {
        "category": "Cooley History",
        "question": "What were the names of Benjamin Cooley's parents, married in 1607 in Tring Parish?",
        "choices": ["Thomas and Mary Cooley", "William Cooley and Joan Arnot", "Richard and Elizabeth Cooley", "Henry Cooley and Anne Baker"],
        "answer": "William Cooley and Joan Arnot",
    },
    {
        "category": "Cooley History",
        "question": "Why were Benjamin Cooley's remains relocated from the original Springfield burying ground in 1848-49?",
        "choices": ["Flooding from the river", "To make room for railroad tracks", "To build a new church", "A cemetery fire"],
        "answer": "To make room for railroad tracks",
    },
    {
        "category": "Cooley History",
        "question": "What geographic feature in Longmeadow, Massachusetts bears the Cooley name?",
        "choices": ["Cooley Mountain", "Cooley Brook", "Lake Cooley", "Cooley Falls"],
        "answer": "Cooley Brook",
    },
    # ── Denton Cooley: Heart Surgeon ──
    {
        "category": "Famous Cooleys",
        "question": "Denton Cooley was a world-renowned surgeon specializing in which field?",
        "choices": ["Neurosurgery", "Orthopedic surgery", "Cardiothoracic surgery", "Plastic surgery"],
        "answer": "Cardiothoracic surgery",
    },
    {
        "category": "Famous Cooleys",
        "question": "In what year did Denton Cooley perform the first total artificial heart implant?",
        "choices": ["1963", "1967", "1969", "1975"],
        "answer": "1969",
    },
    {
        "category": "Famous Cooleys",
        "question": "Denton Cooley founded which major medical institution in Houston, Texas?",
        "choices": ["Mayo Clinic", "Johns Hopkins Heart Center", "Texas Heart Institute", "Cleveland Clinic"],
        "answer": "Texas Heart Institute",
    },
    {
        "category": "Famous Cooleys",
        "question": "In what year did Denton Cooley found the Texas Heart Institute?",
        "choices": ["1955", "1962", "1969", "1974"],
        "answer": "1962",
    },
    {
        "category": "Famous Cooleys",
        "question": "The first total artificial heart implanted by Denton Cooley was co-developed with which physician?",
        "choices": ["Michael DeBakey", "Domingo Liotta", "Christiaan Barnard", "Robert Jarvik"],
        "answer": "Domingo Liotta",
    },
    {
        "category": "Famous Cooleys",
        "question": "Denton Cooley was born in 1920 and passed away in 2016. In which city was he based for most of his career?",
        "choices": ["Dallas", "Houston", "San Antonio", "New York"],
        "answer": "Houston",
    },
    # ── Charles Horton Cooley: Sociologist ──
    {
        "category": "Famous Cooleys",
        "question": "Charles Horton Cooley was a pioneering American sociologist best known for which concept?",
        "choices": ["Social Darwinism", "The looking-glass self", "Collective consciousness", "Anomie"],
        "answer": "The looking-glass self",
    },
    {
        "category": "Famous Cooleys",
        "question": "Charles Horton Cooley introduced the 'looking-glass self' in which 1902 book?",
        "choices": ["The Social Contract", "Human Nature and the Social Order", "The Sociological Imagination", "The Division of Labor"],
        "answer": "Human Nature and the Social Order",
    },
    {
        "category": "Famous Cooleys",
        "question": "At which university did Charles Horton Cooley spend most of his academic career?",
        "choices": ["Harvard", "Yale", "University of Michigan", "Columbia"],
        "answer": "University of Michigan",
    },
    {
        "category": "Famous Cooleys",
        "question": "According to Charles Horton Cooley's 'looking-glass self', how many steps are involved in forming one's self-concept?",
        "choices": ["Two", "Three", "Four", "Five"],
        "answer": "Three",
    },
    {
        "category": "Famous Cooleys",
        "question": "Charles Horton Cooley's ideas laid the groundwork for which sociological school of thought?",
        "choices": ["Functionalism", "Conflict theory", "Symbolic interactionism", "Structuralism"],
        "answer": "Symbolic interactionism",
    },
    # ── Thomas McIntyre Cooley: Jurist ──
    {
        "category": "Famous Cooleys",
        "question": "Thomas McIntyre Cooley served as the first chairman of which U.S. federal agency?",
        "choices": ["Federal Reserve", "Interstate Commerce Commission", "Securities and Exchange Commission", "Federal Trade Commission"],
        "answer": "Interstate Commerce Commission",
    },
    {
        "category": "Famous Cooleys",
        "question": "Thomas McIntyre Cooley served on the Supreme Court of which U.S. state from 1864 to 1885?",
        "choices": ["Ohio", "New York", "Michigan", "Massachusetts"],
        "answer": "Michigan",
    },
    {
        "category": "Famous Cooleys",
        "question": "Which U.S. president appointed Thomas McIntyre Cooley as the first chairman of the Interstate Commerce Commission in 1887?",
        "choices": ["Abraham Lincoln", "Grover Cleveland", "Chester Arthur", "Benjamin Harrison"],
        "answer": "Grover Cleveland",
    },
    {
        "category": "Famous Cooleys",
        "question": "Thomas McIntyre Cooley was one of the first three faculty members and later dean of which law school?",
        "choices": ["Harvard Law School", "Yale Law School", "University of Michigan Law School", "Columbia Law School"],
        "answer": "University of Michigan Law School",
    },
    {
        "category": "Famous Cooleys",
        "question": "Thomas McIntyre Cooley and three colleagues on the Michigan Supreme Court became known by what collective nickname?",
        "choices": ["The Big Four", "The Founding Fathers", "The Iron Bench", "The Legal Eagles"],
        "answer": "The Big Four",
    },
    # ── Cooley's Anemia / Thalassemia ──
    {
        "category": "Cooley Science",
        "question": "Cooley's anemia is another name for which inherited blood disorder?",
        "choices": ["Sickle cell anemia", "Hemophilia", "Thalassemia", "Leukemia"],
        "answer": "Thalassemia",
    },
    {
        "category": "Cooley Science",
        "question": "Cooley's anemia was first described in 1925 by which physician?",
        "choices": ["Denton Cooley", "Thomas Benton Cooley", "Thomas McIntyre Cooley", "Charles Horton Cooley"],
        "answer": "Thomas Benton Cooley",
    },
    {
        "category": "Cooley Science",
        "question": "Thomas Benton Cooley, who described Cooley's anemia, specialized in which field of medicine?",
        "choices": ["Cardiology", "Pediatric hematology", "Neurology", "Orthopedics"],
        "answer": "Pediatric hematology",
    },
    {
        "category": "Cooley Science",
        "question": "Thomas Benton Cooley (the physician) was the son of which famous jurist?",
        "choices": ["Benjamin Cooley", "Thomas McIntyre Cooley", "Mortimer Elwyn Cooley", "Charles Horton Cooley"],
        "answer": "Thomas McIntyre Cooley",
    },
    {
        "category": "Cooley Science",
        "question": "Cooley's anemia (beta thalassemia major) primarily affects the production of which protein in red blood cells?",
        "choices": ["Albumin", "Hemoglobin", "Fibrinogen", "Insulin"],
        "answer": "Hemoglobin",
    },
    {
        "category": "Cooley Science",
        "question": "Thomas Benton Cooley first observed Cooley's anemia in children of which ethnic backgrounds in Detroit?",
        "choices": ["German and Polish", "Irish and Scottish", "Italian and Greek", "Chinese and Japanese"],
        "answer": "Italian and Greek",
    },
    # ── Spade Cooley: Musician ──
    {
        "category": "Famous Cooleys",
        "question": "Spade Cooley was a musician who promoted himself with which royal title?",
        "choices": ["King of Country", "King of Western Swing", "King of Bluegrass", "King of Honky Tonk"],
        "answer": "King of Western Swing",
    },
    {
        "category": "Famous Cooleys",
        "question": "What was Spade Cooley's real first name?",
        "choices": ["Samuel", "David", "Donnell", "Spencer"],
        "answer": "Donnell",
    },
    {
        "category": "Famous Cooleys",
        "question": "Spade Cooley's number-one country hit, recorded in December 1944, was called what?",
        "choices": ["Heartbreak Hotel", "Shame on You", "Crazy Arms", "Walking the Floor Over You"],
        "answer": "Shame on You",
    },
    {
        "category": "Famous Cooleys",
        "question": "Which other musician is widely considered by historians to be the true 'King of Western Swing' over Spade Cooley?",
        "choices": ["Hank Williams", "Bob Wills", "Merle Haggard", "Johnny Cash"],
        "answer": "Bob Wills",
    },
    # ── Mason Cooley: Aphorist ──
    {
        "category": "Famous Cooleys",
        "question": "Mason Cooley (1927-2002) was a noted American writer best known for his work in which literary form?",
        "choices": ["Novels", "Sonnets", "Aphorisms", "Epic poetry"],
        "answer": "Aphorisms",
    },
    {
        "category": "Famous Cooleys",
        "question": "Mason Cooley was a professor emeritus at the College of Staten Island. In which city is that college located?",
        "choices": ["Boston", "Philadelphia", "New York City", "Chicago"],
        "answer": "New York City",
    },
    # ── Cooley Law School ──
    {
        "category": "Cooley Institutions",
        "question": "The Thomas M. Cooley Law School is located in which U.S. state?",
        "choices": ["Ohio", "Michigan", "New York", "Massachusetts"],
        "answer": "Michigan",
    },
    {
        "category": "Cooley Institutions",
        "question": "In which city was the Thomas M. Cooley Law School originally established?",
        "choices": ["Detroit", "Ann Arbor", "Lansing", "Grand Rapids"],
        "answer": "Lansing",
    },
    {
        "category": "Cooley Institutions",
        "question": "The Thomas M. Cooley Law School was founded in 1972 by a group led by Thomas E. Brennan, who was a former Chief Justice of which court?",
        "choices": ["U.S. Supreme Court", "Michigan Supreme Court", "Ohio Supreme Court", "U.S. Court of Appeals"],
        "answer": "Michigan Supreme Court",
    },
    # ── Cooley Peninsula & Mountains (Ireland) ──
    {
        "category": "Cooley Geography",
        "question": "The Cooley Peninsula is located in which Irish county?",
        "choices": ["Cork", "Galway", "Louth", "Kerry"],
        "answer": "Louth",
    },
    {
        "category": "Cooley Geography",
        "question": "What is the highest peak in the Cooley Mountains?",
        "choices": ["Carrauntoohil", "Slieve Foy", "Croagh Patrick", "Mount Brandon"],
        "answer": "Slieve Foy",
    },
    {
        "category": "Cooley Geography",
        "question": "Slieve Foy, the highest peak of the Cooley Mountains, reaches approximately what height?",
        "choices": ["289 metres", "389 metres", "489 metres", "589 metres"],
        "answer": "589 metres",
    },
    # ── Tain Bo Cuailnge (Cattle Raid of Cooley) ──
    {
        "category": "Cooley Mythology",
        "question": "The Tain Bo Cuailnge, or 'Cattle Raid of Cooley', is the central epic of which cycle of Irish mythology?",
        "choices": ["Fenian Cycle", "Mythological Cycle", "Ulster Cycle", "Historical Cycle"],
        "answer": "Ulster Cycle",
    },
    {
        "category": "Cooley Mythology",
        "question": "In the Tain Bo Cuailnge, which queen of Connacht leads the invasion to steal the bull of Cooley?",
        "choices": ["Queen Brigid", "Queen Medb", "Queen Emer", "Queen Deirdre"],
        "answer": "Queen Medb",
    },
    {
        "category": "Cooley Mythology",
        "question": "What is the name of the great brown bull of Cooley that Queen Medb seeks to capture in the Tain?",
        "choices": ["Finnbhennach", "Donn Cuailnge", "Tarb Cuailnge", "Liath Macha"],
        "answer": "Donn Cuailnge",
    },
    # ── Cooley Distillery ──
    {
        "category": "Cooley Institutions",
        "question": "Cooley Distillery, an Irish whiskey distillery on the Cooley Peninsula, was founded in 1987 by which entrepreneur?",
        "choices": ["John Jameson", "John Teeling", "John Power", "John Locke"],
        "answer": "John Teeling",
    },
    {
        "category": "Cooley Institutions",
        "question": "Which peated single malt Irish whiskey is one of the signature brands produced at Cooley Distillery?",
        "choices": ["Jameson", "Bushmills", "Connemara", "Redbreast"],
        "answer": "Connemara",
    },
    {
        "category": "Cooley Institutions",
        "question": "Unlike most Irish whiskeys which are distilled three times, Cooley Distillery's products are generally distilled how many times?",
        "choices": ["Once", "Twice", "Four times", "Five times"],
        "answer": "Twice",
    },
]
