QUESTIONS = [
    # ── Founding & Company Overview ──
    {
        "category": "History of AWH",
        "question": "In what year was AWH Partners founded?",
        "choices": ["2008", "2010", "2012", "2014"],
        "answer": "2010",
    },
    {
        "category": "History of AWH",
        "question": "AWH Partners was formed on the heels of which major economic event?",
        "choices": ["The Dot-Com Bust", "The Great Recession", "The COVID-19 Pandemic", "The 2015 Oil Crisis"],
        "answer": "The Great Recession",
    },
    {
        "category": "History of AWH",
        "question": "AWH Partners was formed by alumni of which two major real estate firms?",
        "choices": ["Goldman Sachs and Brookfield", "The Blackstone Group and The Related Companies", "CBRE and JLL", "Starwood Capital and Cerberus"],
        "answer": "The Blackstone Group and The Related Companies",
    },
    {
        "category": "History of AWH",
        "question": "How much has AWH Partners cumulatively invested in hotel real estate since 2010?",
        "choices": ["Over $500 million", "Over $1 billion", "Over $2 billion", "Over $5 billion"],
        "answer": "Over $2 billion",
    },
    {
        "category": "History of AWH",
        "question": "How many hotel rooms has AWH Partners acquired cumulatively?",
        "choices": ["Over 3,500", "Over 6,000", "Over 9,500", "Over 15,000"],
        "answer": "Over 9,500",
    },
    # ── The Co-Founders ──
    {
        "category": "History of AWH",
        "question": "Where did Russ Flicker earn his undergraduate degree?",
        "choices": ["Duke University", "University of Pennsylvania", "Washington University in St. Louis", "Columbia University"],
        "answer": "Washington University in St. Louis",
    },
    {
        "category": "History of AWH",
        "question": "Where did Russ Flicker earn his law degree?",
        "choices": ["Harvard Law School", "Duke University School of Law", "Columbia Law School", "NYU School of Law"],
        "answer": "Duke University School of Law",
    },
    {
        "category": "History of AWH",
        "question": "What title did Russ Flicker hold at The Trump Organization?",
        "choices": ["General Counsel", "Chief Financial Officer", "Executive Vice President", "Managing Director"],
        "answer": "Executive Vice President",
    },
    {
        "category": "History of AWH",
        "question": "Before co-founding AWH, Russ Flicker served as Chief Investment Officer at which company?",
        "choices": ["Marriott International", "Ian Schrager Company", "Hilton Worldwide", "Four Seasons Hotels"],
        "answer": "Ian Schrager Company",
    },
    {
        "category": "History of AWH",
        "question": "At which firm did Russ Flicker serve as an Operating Partner managing the hospitality development team?",
        "choices": ["KKR", "Blackstone Real Estate Advisors", "Cerberus Capital", "Apollo Global Management"],
        "answer": "Blackstone Real Estate Advisors",
    },
    {
        "category": "History of AWH",
        "question": "How many years did Russ Flicker spend at The Trump Organization?",
        "choices": ["2 years", "5 years", "8 years", "12 years"],
        "answer": "5 years",
    },
    {
        "category": "History of AWH",
        "question": "Where did Jon Rosenfeld earn his undergraduate degree?",
        "choices": ["MIT Sloan", "The Wharton School, University of Pennsylvania", "Harvard Business School", "Stanford University"],
        "answer": "The Wharton School, University of Pennsylvania",
    },
    {
        "category": "History of AWH",
        "question": "Jon Rosenfeld graduated from Wharton with what Latin honor?",
        "choices": ["Cum laude", "Magna cum laude", "Summa cum laude", "Honoris causa"],
        "answer": "Summa cum laude",
    },
    {
        "category": "History of AWH",
        "question": "What were Jon Rosenfeld's dual concentrations at Wharton?",
        "choices": ["Marketing and Management", "Finance and Accounting", "Economics and Statistics", "Real Estate and Finance"],
        "answer": "Finance and Accounting",
    },
    {
        "category": "History of AWH",
        "question": "How many years did Jon Rosenfeld spend at The Blackstone Group?",
        "choices": ["3 years", "5 years", "8 years", "12 years"],
        "answer": "8 years",
    },
    {
        "category": "History of AWH",
        "question": "In his first two years at Blackstone, Jon Rosenfeld worked in which group?",
        "choices": ["Private equity", "Mergers & acquisitions", "Credit and restructuring", "Hedge fund strategies"],
        "answer": "Mergers & acquisitions",
    },
    {
        "category": "History of AWH",
        "question": "Where did Chad Cooley earn his undergraduate degree?",
        "choices": ["Colgate University", "Cornell University", "Dartmouth College", "Williams College"],
        "answer": "Colgate University",
    },
    {
        "category": "History of AWH",
        "question": "What was Chad Cooley's major at Colgate University?",
        "choices": ["Economics", "Political Science", "History", "Business Administration"],
        "answer": "Political Science",
    },
    {
        "category": "History of AWH",
        "question": "What Colgate University graduating class is Chad Cooley a member of?",
        "choices": ["Class of 1996", "Class of 1998", "Class of 2000", "Class of 2002"],
        "answer": "Class of 2000",
    },
    {
        "category": "History of AWH",
        "question": "Before co-founding AWH, Chad Cooley spent approximately 8 years as a Vice President at which firm?",
        "choices": ["The Related Companies", "Tishman Speyer", "Brookfield Asset Management", "Vornado Realty Trust"],
        "answer": "The Related Companies",
    },
    {
        "category": "History of AWH",
        "question": "What role was Chad Cooley welcomed into on Colgate University's Board of Trustees in fall 2023?",
        "choices": ["Honorary Fellow", "Trustee", "Chancellor", "Dean of Alumni"],
        "answer": "Trustee",
    },
    {
        "category": "History of AWH",
        "question": "At ALIS 2026, Chad Cooley predicted what was \"slowly swinging back toward more activity\"?",
        "choices": ["The construction crane", "The deal pendulum", "The interest rate cycle", "The hospitality wheel"],
        "answer": "The deal pendulum",
    },
    # ── Spire Hospitality ──
    {
        "category": "History of AWH",
        "question": "AWH Partners acquired and rebranded a hotel management company as Spire Hospitality. What was its original name?",
        "choices": ["Pinnacle Hospitality", "Lane Hospitality", "Summit Hotel Group", "Bridge Hospitality"],
        "answer": "Lane Hospitality",
    },
    {
        "category": "History of AWH",
        "question": "In what year did AWH Partners acquire and rebrand Lane Hospitality as Spire Hospitality?",
        "choices": ["2010", "2012", "2014", "2016"],
        "answer": "2012",
    },
    {
        "category": "History of AWH",
        "question": "In what year was Lane Hospitality (later Spire Hospitality) originally founded?",
        "choices": ["1970", "1975", "1980", "1985"],
        "answer": "1980",
    },
    {
        "category": "History of AWH",
        "question": "Where is Spire Hospitality headquartered?",
        "choices": ["New York City", "Near Dallas, Texas", "Chicago, Illinois", "Atlanta, Georgia"],
        "answer": "Near Dallas, Texas",
    },
    # ── Chris Russell, CEO of Spire ──
    {
        "category": "History of AWH",
        "question": "Where did Chris Russell, CEO of Spire Hospitality, attend school?",
        "choices": ["Cornell University", "The Culinary Institute of America", "Johnson & Wales", "University of Houston"],
        "answer": "The Culinary Institute of America",
    },
    {
        "category": "History of AWH",
        "question": "What was Chris Russell's first job after graduating from culinary school?",
        "choices": ["Line cook at The Plaza NYC", "Chef at the Four Seasons Houston", "Sous chef at The Ritz-Carlton", "Restaurant manager at Marriott"],
        "answer": "Chef at the Four Seasons Houston",
    },
    {
        "category": "History of AWH",
        "question": "Before joining Spire, Chris Russell built Archon Hospitality from the ground up for which Wall Street firm?",
        "choices": ["Morgan Stanley", "JPMorgan Chase", "Goldman Sachs", "Citigroup"],
        "answer": "Goldman Sachs",
    },
    {
        "category": "History of AWH",
        "question": "At what age did Chris Russell start working in the restaurant business?",
        "choices": ["14", "16", "18", "21"],
        "answer": "16",
    },
    {
        "category": "History of AWH",
        "question": "Chris Russell's operational mantra at Spire Hospitality is what?",
        "choices": ["\"Go big or go home\"", "\"Being the best, not the biggest\"", "\"Excellence in every detail\"", "\"Hospitality without limits\""],
        "answer": "\"Being the best, not the biggest\"",
    },
    # ── AWH Development & Leadership ──
    {
        "category": "History of AWH",
        "question": "Who was hired as President of AWH Development in January 2017?",
        "choices": ["Dev Sharma", "Timothy Osiecki", "Michael Chen", "Robert Franklin"],
        "answer": "Timothy Osiecki",
    },
    {
        "category": "History of AWH",
        "question": "Before joining AWH, Timothy Osiecki spent three decades at which hospitality company?",
        "choices": ["Marriott International", "Concord Hospitality", "Hilton Worldwide", "Hyatt Hotels"],
        "answer": "Concord Hospitality",
    },
    {
        "category": "History of AWH",
        "question": "Timothy Osiecki led the design team responsible for the first LEED-certified prototype of which Marriott brand?",
        "choices": ["Fairfield Inn", "Courtyard by Marriott", "Residence Inn", "SpringHill Suites"],
        "answer": "Courtyard by Marriott",
    },
    {
        "category": "History of AWH",
        "question": "What first-ever award did Timothy Osiecki receive from Marriott?",
        "choices": ["The Pioneer Award", "The Icon Award", "The Visionary Award", "The Innovation Prize"],
        "answer": "The Icon Award",
    },
    # ── MIDAS & Technology ──
    {
        "category": "History of AWH",
        "question": "What does AWH's proprietary platform \"MIDAS\" stand for?",
        "choices": ["Market Intelligence Data Analytics System", "Managed Investment & Deal Acquisition Software", "Multi-Industry Data Analysis Suite", "Market Insights & Digital Asset Scoring"],
        "answer": "Market Intelligence Data Analytics System",
    },
    {
        "category": "History of AWH",
        "question": "AWH created MIDAS after how many years of harvesting, cleaning, and organizing data?",
        "choices": ["Over 5 years", "Over a decade", "Over 20 years", "Over 2 years"],
        "answer": "Over a decade",
    },
    {
        "category": "History of AWH",
        "question": "According to AWH's HouseView, MIDAS augments what critical resource?",
        "choices": ["Artificial intelligence", "External consultants", "In-house human intelligence", "Third-party data vendors"],
        "answer": "In-house human intelligence",
    },
    {
        "category": "History of AWH",
        "question": "AWH Partners built a proprietary data-driven platform that tracks how many hospitality markets?",
        "choices": ["100+", "300+", "600+", "1,000+"],
        "answer": "600+",
    },
    {
        "category": "History of AWH",
        "question": "AWH's digital intelligence platform has aggregated how many years of investment and market data?",
        "choices": ["5+", "10+", "15+", "25+"],
        "answer": "15+",
    },
    {
        "category": "History of AWH",
        "question": "Which AWH acquisition was the first deal identified primarily using their proprietary digital intelligence platform?",
        "choices": ["Hotel Trio Healdsburg", "Residence Inn/Fairfield Inn Broomfield, CO", "The Barnes San Francisco", "DoubleTree Albuquerque"],
        "answer": "Residence Inn/Fairfield Inn Broomfield, CO",
    },
    # ── AWH Strategic Income Fund ──
    {
        "category": "History of AWH",
        "question": "When was the AWH Strategic Income Fund announced?",
        "choices": ["January 2024", "August 2025", "February 2026", "December 2023"],
        "answer": "August 2025",
    },
    {
        "category": "History of AWH",
        "question": "What was the initial committed capital for the AWH Strategic Income Fund?",
        "choices": ["$5 million", "$20 million", "$50 million", "$100 million"],
        "answer": "$20 million",
    },
    {
        "category": "History of AWH",
        "question": "What is the target size of the AWH Strategic Income Fund?",
        "choices": ["$50 million", "$100 million", "$250 million", "$500 million"],
        "answer": "$100 million",
    },
    {
        "category": "History of AWH",
        "question": "What is the target deal size per transaction for the AWH Strategic Income Fund?",
        "choices": ["$1M to $5M", "$5M to $15M", "$15M to $50M", "$50M to $100M"],
        "answer": "$15M to $50M",
    },
    {
        "category": "History of AWH",
        "question": "What was the first acquisition made by the AWH Strategic Income Fund?",
        "choices": ["Residence Inn Broomfield", "Hotel Trio Healdsburg", "The Barnes San Francisco", "DoubleTree Albuquerque"],
        "answer": "Hotel Trio Healdsburg",
    },
    # ── Notable Deals ──
    {
        "category": "History of AWH",
        "question": "What was AWH Partners' first major acquisition - a distressed Orlando hotel purchased for $22 million?",
        "choices": ["Hilton Orlando", "Sheraton Safari Hotel & Suites", "DoubleTree at SeaWorld", "The Grove Resort"],
        "answer": "Sheraton Safari Hotel & Suites",
    },
    {
        "category": "History of AWH",
        "question": "The Sheraton Safari Hotel was converted and rebranded to what name after AWH's renovation?",
        "choices": ["Sheraton Orlando Resort", "Sheraton Lake Buena Vista Resort", "Sheraton Safari Resort & Spa", "Sheraton Disney Springs"],
        "answer": "Sheraton Lake Buena Vista Resort",
    },
    {
        "category": "History of AWH",
        "question": "For approximately how much did AWH sell the Sheraton Lake Buena Vista Resort in February 2021?",
        "choices": ["$22 million", "$35 million", "$49.8 million", "$75 million"],
        "answer": "$49.8 million",
    },
    {
        "category": "History of AWH",
        "question": "In January 2014, AWH acquired a portfolio of how many Embassy Suites hotels through a bankruptcy process?",
        "choices": ["4", "6", "8", "12"],
        "answer": "8",
    },
    {
        "category": "History of AWH",
        "question": "What was the estimated valuation of AWH's 2014 eight-hotel Embassy Suites portfolio?",
        "choices": ["$80 million", "~$170 million", "$250 million", "$350 million"],
        "answer": "~$170 million",
    },
    {
        "category": "History of AWH",
        "question": "How much did AWH invest in physical upgrades to the eight Embassy Suites properties?",
        "choices": ["$10 million", "Over $75 million", "$100 million", "$150 million"],
        "answer": "Over $75 million",
    },
    {
        "category": "History of AWH",
        "question": "AWH's Waterstone Resort & Marina in Boca Raton won which Hilton brand award in 2014?",
        "choices": ["Hotel of the Year", "DoubleTree Development of the Year", "Hilton Innovation Award", "Best New Property"],
        "answer": "DoubleTree Development of the Year",
    },
    {
        "category": "History of AWH",
        "question": "The January 2015 acquisition of the LA Marriott Burbank Airport was AWH's first joint venture with which partner?",
        "choices": ["Apollo Global Management", "The Roxborough Group", "Starr Companies", "Building and Land Technology"],
        "answer": "Starr Companies",
    },
    {
        "category": "History of AWH",
        "question": "The LA Marriott Burbank Airport acquisition in 2015 pushed AWH past what investment milestone?",
        "choices": ["$100 million", "The half-billion-dollar mark", "$1 billion", "$2 billion"],
        "answer": "The half-billion-dollar mark",
    },
    {
        "category": "History of AWH",
        "question": "In July 2016, AWH acquired the Seattle Airport Marriott from which major hotel REIT?",
        "choices": ["Pebblebrook Hotel Trust", "RLJ Lodging Trust", "Host Hotels & Resorts", "Park Hotels & Resorts"],
        "answer": "Host Hotels & Resorts",
    },
    {
        "category": "History of AWH",
        "question": "AWH's DoubleTree by Hilton Albuquerque is the only hotel directly connected to what?",
        "choices": ["The Albuquerque International Airport", "The Albuquerque Convention Center", "The University of New Mexico campus", "Old Town Albuquerque"],
        "answer": "The Albuquerque Convention Center",
    },
    {
        "category": "History of AWH",
        "question": "AWH's Embassy Suites Laredo is the only full-service branded hotel in that market. Laredo is known as what along the US-Mexico border?",
        "choices": ["The oldest crossing", "The largest port", "The busiest checkpoint", "The gateway city"],
        "answer": "The largest port",
    },
    {
        "category": "History of AWH",
        "question": "Which February 2021 deal was the first hotel acquisition AWH closed following the start of the COVID-19 pandemic?",
        "choices": ["Villa Florence San Francisco", "Hilton Garden Inn Portland/Lake Oswego", "Kimpton Goodland Goleta", "DoubleTree Anaheim"],
        "answer": "Hilton Garden Inn Portland/Lake Oswego",
    },
    {
        "category": "History of AWH",
        "question": "AWH acquired the Villa Florence Hotel near Union Square in San Francisco for how much?",
        "choices": ["$45 million", "$65 million", "$87.5 million", "$120 million"],
        "answer": "$87.5 million",
    },
    {
        "category": "History of AWH",
        "question": "The Villa Florence was later rebranded to what name under the Tapestry Collection by Hilton?",
        "choices": ["The Powell", "The Union", "The Barnes", "The Florence"],
        "answer": "The Barnes",
    },
    {
        "category": "History of AWH",
        "question": "AWH partnered with funds managed by which global investment firm for the DoubleTree Anaheim acquisition?",
        "choices": ["Blackstone", "KKR", "Apollo Global Management", "Carlyle Group"],
        "answer": "Apollo Global Management",
    },
    {
        "category": "History of AWH",
        "question": "The Hilton Garden Inn Fremont Milpitas is located adjacent to which company's flagship Silicon Valley factory?",
        "choices": ["Apple", "Google", "Tesla", "Meta"],
        "answer": "Tesla",
    },
    {
        "category": "History of AWH",
        "question": "AWH acquired the Kimpton Goodland near Santa Barbara and rebranded it to what?",
        "choices": ["The Goleta", "The Leta", "The Coast", "The Pacific"],
        "answer": "The Leta",
    },
    {
        "category": "History of AWH",
        "question": "The Grove Resort & Water Park in Orlando sits on how many acres?",
        "choices": ["42 acres", "78 acres", "106 acres", "150 acres"],
        "answer": "106 acres",
    },
    # ── More Deal Details ──
    {
        "category": "History of AWH",
        "question": "What was the purchase price per key for AWH's November 2024 Broomfield, CO dual-branded Marriott acquisition?",
        "choices": ["$95,000", "$137,000", "$211,000", "$311,000"],
        "answer": "$137,000",
    },
    {
        "category": "History of AWH",
        "question": "What was the going-in cap rate on AWH's Broomfield, CO acquisition?",
        "choices": ["5.5%", "7.0%", "9.5%", "12.0%"],
        "answer": "9.5%",
    },
    {
        "category": "History of AWH",
        "question": "Hotel Trio Healdsburg, AWH's February 2026 acquisition, is the only property of which brand in northern Sonoma County?",
        "choices": ["Hilton", "Marriott", "Hyatt", "IHG"],
        "answer": "Marriott",
    },
    {
        "category": "History of AWH",
        "question": "What is the projected net levered IRR for the Hotel Trio Healdsburg investment?",
        "choices": ["8.5%", "12.25%", "17.40%", "22.00%"],
        "answer": "17.40%",
    },
    # ── Development & Awards ──
    {
        "category": "History of AWH",
        "question": "AWH's proposed new-build hotel in Burbank would be how many guest rooms across two brands?",
        "choices": ["260 rooms", "340 rooms", "420 rooms", "500 rooms"],
        "answer": "420 rooms",
    },
    {
        "category": "History of AWH",
        "question": "The proposed Burbank dual-branded hotel holds the distinction of being the city's first what?",
        "choices": ["High-rise hotel", "All-electric hotel", "Rooftop pool hotel", "Convention hotel"],
        "answer": "All-electric hotel",
    },
    {
        "category": "History of AWH",
        "question": "Which two hotel brands are planned for AWH's new Burbank development?",
        "choices": ["Marriott & Westin", "Hilton Garden Inn & Hampton", "Aloft & Residence Inn", "Hyatt Place & Hyatt House"],
        "answer": "Aloft & Residence Inn",
    },
    {
        "category": "History of AWH",
        "question": "Which AWH property won the Starwood Hotels and Resorts \"Renovation of the Year\" award?",
        "choices": ["Seattle Airport Marriott", "Sheraton Lake Buena Vista Resort", "Waterstone Resort & Marina", "DoubleTree Orlando at SeaWorld"],
        "answer": "Sheraton Lake Buena Vista Resort",
    },
]
