QUESTIONS = [
    # ── Math Challenges ──
    {
        "category": "Math",
        "question": "What is 17 × 6?",
        "choices": ["92", "96", "102", "108"],
        "answer": "102",
    },
    {
        "category": "Math",
        "question": "What is 144 ÷ 12?",
        "choices": ["10", "11", "12", "14"],
        "answer": "12",
    },
    {
        "category": "Math",
        "question": "If you buy 3 items at $4.50 each, what is the total?",
        "choices": ["$12.00", "$13.50", "$14.50", "$15.00"],
        "answer": "$13.50",
    },
    {
        "category": "Math",
        "question": "What is the next number in the pattern: 2, 6, 18, 54, ...?",
        "choices": ["108", "162", "72", "96"],
        "answer": "162",
    },
    {
        "category": "Math",
        "question": "How many seconds are in one hour?",
        "choices": ["360", "3600", "600", "36000"],
        "answer": "3600",
    },
    {
        "category": "Math",
        "question": "What is 25% of 200?",
        "choices": ["25", "40", "50", "75"],
        "answer": "50",
    },
    {
        "category": "Math",
        "question": "A rectangle has sides of 8 and 5. What is its area?",
        "choices": ["13", "26", "40", "45"],
        "answer": "40",
    },
    {
        "category": "Math",
        "question": "What is 9 squared?",
        "choices": ["18", "72", "81", "99"],
        "answer": "81",
    },
    # ── Logic Puzzles ──
    {
        "category": "Logic",
        "question": "If all Bloops are Razzles and all Razzles are Lazzles, are all Bloops definitely Lazzles?",
        "choices": ["Yes", "No", "Maybe", "Not enough info"],
        "answer": "Yes",
    },
    {
        "category": "Logic",
        "question": "I have cities but no houses, forests but no trees, and water but no fish. What am I?",
        "choices": ["A dream", "A map", "A painting", "A story"],
        "answer": "A map",
    },
    {
        "category": "Logic",
        "question": "A farmer has 17 sheep. All but 9 run away. How many sheep does he have left?",
        "choices": ["8", "9", "17", "0"],
        "answer": "9",
    },
    {
        "category": "Logic",
        "question": "Which weighs more: a pound of feathers or a pound of bricks?",
        "choices": ["Feathers", "Bricks", "They weigh the same", "Depends on gravity"],
        "answer": "They weigh the same",
    },
    {
        "category": "Logic",
        "question": "If there are 3 apples and you take away 2, how many apples do YOU have?",
        "choices": ["1", "2", "3", "0"],
        "answer": "2",
    },
    {
        "category": "Logic",
        "question": "What comes once in a minute, twice in a moment, but never in a thousand years?",
        "choices": ["The letter M", "Time", "A second", "Nothing"],
        "answer": "The letter M",
    },
    {
        "category": "Logic",
        "question": "A is the father of B. But B is not the son of A. How is that possible?",
        "choices": ["B is adopted", "B is A's daughter", "They are not related", "A is lying"],
        "answer": "B is A's daughter",
    },
    {
        "category": "Logic",
        "question": "How many months have 28 days?",
        "choices": ["1", "2", "6", "All 12"],
        "answer": "All 12",
    },
    # ── Word Puzzles ──
    {
        "category": "Words",
        "question": "Unscramble this word: ZZLEPU",
        "choices": ["PUZZLE", "MUZZLE", "FIZZLE", "NUZZLE"],
        "answer": "PUZZLE",
    },
    {
        "category": "Words",
        "question": "Which word means the OPPOSITE of 'ancient'?",
        "choices": ["Old", "Historic", "Modern", "Classic"],
        "answer": "Modern",
    },
    {
        "category": "Words",
        "question": "What 5-letter word becomes shorter when you add two letters to it?",
        "choices": ["Small", "Short", "Brief", "Tiny"],
        "answer": "Short",
    },
    {
        "category": "Words",
        "question": "Unscramble: CIENSCE",
        "choices": ["SILENCE", "SCIENCE", "LICENSE", "SCENICE"],
        "answer": "SCIENCE",
    },
    {
        "category": "Words",
        "question": "Which word does NOT belong: Apple, Banana, Carrot, Grape?",
        "choices": ["Apple", "Banana", "Carrot", "Grape"],
        "answer": "Carrot",
    },
    {
        "category": "Words",
        "question": "What word is spelled incorrectly in every dictionary?",
        "choices": ["Pneumonia", "Incorrectly", "Rhythm", "Onomatopoeia"],
        "answer": "Incorrectly",
    },
    # ── Trivia ──
    {
        "category": "Trivia",
        "question": "How many planets are in our solar system?",
        "choices": ["7", "8", "9", "10"],
        "answer": "8",
    },
    {
        "category": "Trivia",
        "question": "What is the largest ocean on Earth?",
        "choices": ["Atlantic", "Indian", "Pacific", "Arctic"],
        "answer": "Pacific",
    },
    {
        "category": "Trivia",
        "question": "What gas do plants absorb from the atmosphere?",
        "choices": ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"],
        "answer": "Carbon Dioxide",
    },
    {
        "category": "Trivia",
        "question": "How many sides does a hexagon have?",
        "choices": ["5", "6", "7", "8"],
        "answer": "6",
    },
    {
        "category": "Trivia",
        "question": "Which animal is known as the 'King of the Jungle'?",
        "choices": ["Tiger", "Elephant", "Lion", "Gorilla"],
        "answer": "Lion",
    },
    {
        "category": "Trivia",
        "question": "What is the boiling point of water in Fahrenheit?",
        "choices": ["100°", "200°", "212°", "220°"],
        "answer": "212°",
    },
    {
        "category": "Trivia",
        "question": "What is the hardest natural substance on Earth?",
        "choices": ["Gold", "Iron", "Diamond", "Quartz"],
        "answer": "Diamond",
    },
    {
        "category": "Trivia",
        "question": "Which planet is closest to the Sun?",
        "choices": ["Venus", "Mercury", "Mars", "Earth"],
        "answer": "Mercury",
    },
    # ── Strategy / Would You Rather (opinion-based speed rounds) ──
    {
        "category": "Speed Round",
        "question": "Quick! Pick the LARGEST number:",
        "choices": ["999", "10001", "9999", "1001"],
        "answer": "10001",
    },
    {
        "category": "Speed Round",
        "question": "Which of these is NOT a primary color of paint?",
        "choices": ["Red", "Blue", "Green", "Yellow"],
        "answer": "Green",
    },
    {
        "category": "Speed Round",
        "question": "How many legs does a spider have?",
        "choices": ["6", "8", "10", "12"],
        "answer": "8",
    },
    {
        "category": "Speed Round",
        "question": "What shape has the most sides: triangle, square, pentagon, or hexagon?",
        "choices": ["Triangle", "Square", "Pentagon", "Hexagon"],
        "answer": "Hexagon",
    },
    # ── Picture Round (Emoji) ──
    {
        "category": "Picture Round",
        "question": "What animal is this?",
        "image": {"type": "emoji", "content": "\U0001F98A"},
        "choices": ["Wolf", "Fox", "Dog", "Coyote"],
        "answer": "Fox",
    },
    {
        "category": "Picture Round",
        "question": "What animal is this?",
        "image": {"type": "emoji", "content": "\U0001F419"},
        "choices": ["Squid", "Jellyfish", "Octopus", "Starfish"],
        "answer": "Octopus",
    },
    {
        "category": "Picture Round",
        "question": "What fruit is this?",
        "image": {"type": "emoji", "content": "\U0001F34D"},
        "choices": ["Mango", "Pineapple", "Papaya", "Durian"],
        "answer": "Pineapple",
    },
    {
        "category": "Picture Round",
        "question": "What instrument is this?",
        "image": {"type": "emoji", "content": "\U0001F3B7"},
        "choices": ["Trumpet", "Clarinet", "Saxophone", "Trombone"],
        "answer": "Saxophone",
    },
    {
        "category": "Picture Round",
        "question": "What sport is this?",
        "image": {"type": "emoji", "content": "\U0001F3D3"},
        "choices": ["Tennis", "Badminton", "Table Tennis", "Squash"],
        "answer": "Table Tennis",
    },
    {
        "category": "Picture Round",
        "question": "What does this emoji represent?",
        "image": {"type": "emoji", "content": "\U0001F3F0"},
        "choices": ["Church", "Castle", "Palace", "Fortress"],
        "answer": "Castle",
    },
    {
        "category": "Picture Round",
        "question": "What animal is this?",
        "image": {"type": "emoji", "content": "\U0001F9AB"},
        "choices": ["Beaver", "Otter", "Platypus", "Muskrat"],
        "answer": "Beaver",
    },
    {
        "category": "Picture Round",
        "question": "What is this object?",
        "image": {"type": "emoji", "content": "\U0001FA90"},
        "choices": ["Compass", "Gyroscope", "Yo-Yo", "Spinning Top"],
        "answer": "Yo-Yo",
    },
    # ── Picture Round (Flags — hosted images) ──
    {
        "category": "Picture Round",
        "question": "Which country does this flag belong to?",
        "image": {"type": "url", "src": "https://flagcdn.com/w320/jp.png", "alt": "A country flag"},
        "choices": ["China", "Japan", "South Korea", "Bangladesh"],
        "answer": "Japan",
    },
    {
        "category": "Picture Round",
        "question": "Which country does this flag belong to?",
        "image": {"type": "url", "src": "https://flagcdn.com/w320/br.png", "alt": "A country flag"},
        "choices": ["Brazil", "Portugal", "Bolivia", "Colombia"],
        "answer": "Brazil",
    },
    {
        "category": "Picture Round",
        "question": "Which country does this flag belong to?",
        "image": {"type": "url", "src": "https://flagcdn.com/w320/ca.png", "alt": "A country flag"},
        "choices": ["United States", "Canada", "Switzerland", "Peru"],
        "answer": "Canada",
    },
    {
        "category": "Picture Round",
        "question": "Which country does this flag belong to?",
        "image": {"type": "url", "src": "https://flagcdn.com/w320/za.png", "alt": "A country flag"},
        "choices": ["Kenya", "Nigeria", "South Africa", "Ghana"],
        "answer": "South Africa",
    },
    {
        "category": "Picture Round",
        "question": "Which country does this flag belong to?",
        "image": {"type": "url", "src": "https://flagcdn.com/w320/in.png", "alt": "A country flag"},
        "choices": ["India", "Ireland", "Italy", "Iran"],
        "answer": "India",
    },
    {
        "category": "Picture Round",
        "question": "Which country does this flag belong to?",
        "image": {"type": "url", "src": "https://flagcdn.com/w320/de.png", "alt": "A country flag"},
        "choices": ["Belgium", "Germany", "Netherlands", "Luxembourg"],
        "answer": "Germany",
    },
    {
        "category": "Picture Round",
        "question": "Which country does this flag belong to?",
        "image": {"type": "url", "src": "https://flagcdn.com/w320/au.png", "alt": "A country flag"},
        "choices": ["New Zealand", "Australia", "Fiji", "United Kingdom"],
        "answer": "Australia",
    },
    {
        "category": "Picture Round",
        "question": "Which country does this flag belong to?",
        "image": {"type": "url", "src": "https://flagcdn.com/w320/mx.png", "alt": "A country flag"},
        "choices": ["Italy", "Mexico", "Hungary", "Ireland"],
        "answer": "Mexico",
    },
    # ── Minecraft & Roblox ──
    {
        "category": "Minecraft",
        "question": "What is the name of the final boss in Minecraft?",
        "choices": ["Wither", "Ender Dragon", "Elder Guardian", "Warden"],
        "answer": "Ender Dragon",
    },
    {
        "category": "Minecraft",
        "question": "How many obsidian blocks do you need to build a Nether portal?",
        "choices": ["8", "10", "12", "14"],
        "answer": "10",
    },
    {
        "category": "Minecraft",
        "question": "What do you get when you smelt iron ore?",
        "choices": ["Iron Nugget", "Iron Ingot", "Iron Block", "Raw Iron"],
        "answer": "Iron Ingot",
    },
    {
        "category": "Minecraft",
        "question": "Which mob explodes when it gets close to you?",
        "image": {"type": "emoji", "content": "\U0001F4A5"},
        "choices": ["Zombie", "Skeleton", "Creeper", "Enderman"],
        "answer": "Creeper",
    },
    {
        "category": "Minecraft",
        "question": "What material do you need to mine diamonds?",
        "choices": ["Stone Pickaxe", "Iron Pickaxe", "Gold Pickaxe", "Wooden Pickaxe"],
        "answer": "Iron Pickaxe",
    },
    {
        "category": "Roblox",
        "question": "What is the in-game currency in Roblox?",
        "choices": ["Robux", "V-Bucks", "Coins", "Gems"],
        "answer": "Robux",
    },
    {
        "category": "Roblox",
        "question": "What programming language are Roblox games scripted in?",
        "choices": ["Python", "JavaScript", "Lua", "C++"],
        "answer": "Lua",
    },
    {
        "category": "Roblox",
        "question": "What is the name of the Roblox game-creation tool?",
        "choices": ["Roblox Creator", "Roblox Studio", "Roblox Builder", "Roblox Workshop"],
        "answer": "Roblox Studio",
    },
    {
        "category": "Roblox",
        "question": "In Roblox, what are player-created games called?",
        "choices": ["Worlds", "Experiences", "Levels", "Servers"],
        "answer": "Experiences",
    },
    {
        "category": "Minecraft",
        "question": "What dimension do you enter through an End Portal?",
        "choices": ["The Nether", "The End", "The Aether", "The Void"],
        "answer": "The End",
    },
    # ── More Text Questions ──
    {
        "category": "Math",
        "question": "What is the square root of 144?",
        "choices": ["10", "11", "12", "14"],
        "answer": "12",
    },
    {
        "category": "Math",
        "question": "What is 15% of 80?",
        "choices": ["8", "10", "12", "15"],
        "answer": "12",
    },
    {
        "category": "Logic",
        "question": "If you rearrange the letters 'CIFAIPC', you get the name of a(n):",
        "choices": ["City", "Animal", "Ocean", "Country"],
        "answer": "Ocean",
    },
    {
        "category": "Logic",
        "question": "A bat and a ball cost $1.10 together. The bat costs $1.00 more than the ball. How much does the ball cost?",
        "choices": ["$0.10", "$0.05", "$0.15", "$0.01"],
        "answer": "$0.05",
    },
    {
        "category": "Words",
        "question": "Which word is a palindrome?",
        "choices": ["LEVEL", "LEVER", "LEMON", "LLAMA"],
        "answer": "LEVEL",
    },
    {
        "category": "Words",
        "question": "Unscramble: OEALNMWERT",
        "choices": ["WATERMELON", "TRAMPOLINE", "METRONOME", "Melbourne"],
        "answer": "WATERMELON",
    },
    {
        "category": "Trivia",
        "question": "What is the smallest country in the world by area?",
        "choices": ["Monaco", "Vatican City", "San Marino", "Liechtenstein"],
        "answer": "Vatican City",
    },
    {
        "category": "Trivia",
        "question": "What element does 'O' represent on the periodic table?",
        "choices": ["Osmium", "Oganesson", "Oxygen", "Gold"],
        "answer": "Oxygen",
    },
    {
        "category": "Trivia",
        "question": "Which planet has the most moons?",
        "choices": ["Jupiter", "Saturn", "Uranus", "Neptune"],
        "answer": "Saturn",
    },
    # ── YouTubers ──
    {
        "category": "YouTubers",
        "question": "Which YouTuber is famous for giving away millions of dollars and extreme challenges?",
        "choices": ["PewDiePie", "MrBeast", "Markiplier", "DanTDM"],
        "answer": "MrBeast",
    },
    {
        "category": "YouTubers",
        "question": "What is MrBeast's real first name?",
        "choices": ["Jimmy", "James", "Jake", "Jordan"],
        "answer": "Jimmy",
    },
    {
        "category": "YouTubers",
        "question": "Which YouTuber was once the most subscribed individual creator and is known for meme reviews?",
        "choices": ["Ninja", "MrBeast", "PewDiePie", "KSI"],
        "answer": "PewDiePie",
    },
    {
        "category": "YouTubers",
        "question": "Which Minecraft YouTuber is known for speedruns and the Dream SMP?",
        "choices": ["Technoblade", "Dream", "Skeppy", "Philza"],
        "answer": "Dream",
    },
    {
        "category": "YouTubers",
        "question": "Which YouTuber is known for the Diamond Minecart series?",
        "choices": ["Unspeakable", "SSundee", "DanTDM", "Preston"],
        "answer": "DanTDM",
    },
    {
        "category": "YouTubers",
        "question": "Which YouTuber is known for trick shots and sports challenges with a group of friends?",
        "choices": ["Dude Perfect", "MrBeast", "Ninja", "Jelly"],
        "answer": "Dude Perfect",
    },
    {
        "category": "YouTubers",
        "question": "Which Minecraft YouTuber was known as 'The Blade' and for never dying?",
        "choices": ["Dream", "Technoblade", "Philza", "Sapnap"],
        "answer": "Technoblade",
    },
    {
        "category": "YouTubers",
        "question": "Which YouTuber says 'Was that the bite of '87?!' and is known for horror game playthroughs?",
        "choices": ["Jacksepticeye", "PewDiePie", "Markiplier", "CoryxKenshin"],
        "answer": "Markiplier",
    },
    {
        "category": "YouTubers",
        "question": "Which YouTuber is known for Roblox content and the 'Albert' channel?",
        "choices": ["Denis", "Flamingo", "Jelly", "Kreekcraft"],
        "answer": "Flamingo",
    },
    {
        "category": "YouTubers",
        "question": "Which content creator became famous for streaming Fortnite and has blue hair?",
        "choices": ["Ninja", "Tfue", "Lazarbeam", "SypherPK"],
        "answer": "Ninja",
    },
    {
        "category": "YouTubers",
        "question": "Which YouTuber is known for Minecraft and Roblox videos and saying 'What's up guys, SSundee here'?",
        "choices": ["DanTDM", "SSundee", "Preston", "Unspeakable"],
        "answer": "SSundee",
    },
    {
        "category": "YouTubers",
        "question": "Which female YouTuber is one of the most popular Minecraft content creators with roleplay stories?",
        "choices": ["LDShadowLady", "Aphmau", "iHasCupquake", "Stacy"],
        "answer": "Aphmau",
    },
    {
        "category": "YouTubers",
        "question": "Which YouTuber is known for crazy Minecraft builds and water park challenges?",
        "choices": ["Preston", "Unspeakable", "Jelly", "Kwebbelkop"],
        "answer": "Unspeakable",
    },
    {
        "category": "YouTubers",
        "question": "Which YouTuber runs the channels PrestonPlayz and TBNRFrags?",
        "choices": ["SSundee", "Unspeakable", "Preston", "Lazarbeam"],
        "answer": "Preston",
    },
    {
        "category": "YouTubers",
        "question": "Which YouTuber is known for funny gaming videos and is part of the 'Traffic Light Squad' with Slogo and Crainer?",
        "choices": ["Flamingo", "Jelly", "Kwebbelkop", "Lazarbeam"],
        "answer": "Jelly",
    },
    # ── More Math ──
    {
        "category": "Math",
        "question": "What is 13 × 7?",
        "choices": ["84", "87", "91", "97"],
        "answer": "91",
    },
    {
        "category": "Math",
        "question": "What is 1000 ÷ 8?",
        "choices": ["120", "125", "130", "150"],
        "answer": "125",
    },
    {
        "category": "Math",
        "question": "What is 3/4 as a decimal?",
        "choices": ["0.25", "0.50", "0.75", "0.80"],
        "answer": "0.75",
    },
    {
        "category": "Math",
        "question": "If a triangle has angles of 90° and 45°, what is the third angle?",
        "choices": ["30°", "45°", "55°", "60°"],
        "answer": "45°",
    },
    {
        "category": "Math",
        "question": "What is the next prime number after 7?",
        "choices": ["8", "9", "10", "11"],
        "answer": "11",
    },
    {
        "category": "Math",
        "question": "How many centimeters are in 2.5 meters?",
        "choices": ["25", "250", "2500", "200"],
        "answer": "250",
    },
    {
        "category": "Math",
        "question": "What is 2 to the power of 8?",
        "choices": ["64", "128", "256", "512"],
        "answer": "256",
    },
    # ── More Logic ──
    {
        "category": "Logic",
        "question": "If it takes 5 machines 5 minutes to make 5 widgets, how long would it take 100 machines to make 100 widgets?",
        "choices": ["100 minutes", "50 minutes", "10 minutes", "5 minutes"],
        "answer": "5 minutes",
    },
    {
        "category": "Logic",
        "question": "A doctor gives you 3 pills and says take one every 30 minutes. How long do the pills last?",
        "choices": ["30 minutes", "60 minutes", "90 minutes", "120 minutes"],
        "answer": "60 minutes",
    },
    {
        "category": "Logic",
        "question": "What can you hold in your right hand but never in your left hand?",
        "choices": ["A ball", "Your left elbow", "A pen", "Your breath"],
        "answer": "Your left elbow",
    },
    {
        "category": "Logic",
        "question": "If you overtake the person in 2nd place in a race, what place are you in?",
        "choices": ["1st", "2nd", "3rd", "It depends"],
        "answer": "2nd",
    },
    {
        "category": "Logic",
        "question": "Which is heavier: 100 pounds of rocks or 100 pounds of cotton candy?",
        "choices": ["Rocks", "Cotton candy", "They weigh the same", "Depends on volume"],
        "answer": "They weigh the same",
    },
    {
        "category": "Logic",
        "question": "A man builds a house with all 4 sides facing south. A bear walks past. What color is the bear?",
        "choices": ["Brown", "Black", "White", "Gray"],
        "answer": "White",
    },
    {
        "category": "Logic",
        "question": "What has a head and a tail but no body?",
        "choices": ["A snake", "A coin", "A worm", "A needle"],
        "answer": "A coin",
    },
    # ── More Words ──
    {
        "category": "Words",
        "question": "Unscramble: TALBOFLO",
        "choices": ["FOOTBALL", "FOOTFALL", "BOATFULL", "TALLBOOT"],
        "answer": "FOOTBALL",
    },
    {
        "category": "Words",
        "question": "Which word means a fear of spiders?",
        "choices": ["Claustrophobia", "Arachnophobia", "Acrophobia", "Agoraphobia"],
        "answer": "Arachnophobia",
    },
    {
        "category": "Words",
        "question": "Which of these words uses ONLY the letters A, B, C, D, and E?",
        "choices": ["BRAID", "DECADE", "BEADED", "BACKED"],
        "answer": "BEADED",
    },
    {
        "category": "Words",
        "question": "Which word is an antonym of 'generous'?",
        "choices": ["Kind", "Greedy", "Wealthy", "Cheerful"],
        "answer": "Greedy",
    },
    {
        "category": "Words",
        "question": "Unscramble: NAABRAI",
        "choices": ["BANANA", "ARABIAN", "NIAGARA", "BANDANA"],
        "answer": "ARABIAN",
    },
    {
        "category": "Words",
        "question": "Which of these is a compound word?",
        "choices": ["Butterfly", "Beautiful", "Wonderful", "Powerful"],
        "answer": "Butterfly",
    },
    {
        "category": "Words",
        "question": "What word can follow 'sun', 'moon', and 'star' to make new words?",
        "choices": ["Shine", "Light", "Glow", "Beam"],
        "answer": "Light",
    },
    # ── More Trivia ──
    {
        "category": "Trivia",
        "question": "What is the fastest land animal?",
        "choices": ["Lion", "Horse", "Cheetah", "Greyhound"],
        "answer": "Cheetah",
    },
    {
        "category": "Trivia",
        "question": "How many bones does an adult human have?",
        "choices": ["186", "206", "226", "256"],
        "answer": "206",
    },
    {
        "category": "Trivia",
        "question": "What is the largest continent?",
        "choices": ["Africa", "North America", "Europe", "Asia"],
        "answer": "Asia",
    },
    {
        "category": "Trivia",
        "question": "What is the chemical formula for water?",
        "choices": ["CO2", "H2O", "O2", "NaCl"],
        "answer": "H2O",
    },
    {
        "category": "Trivia",
        "question": "Which is the only mammal that can fly?",
        "choices": ["Flying squirrel", "Bat", "Sugar glider", "Pterodactyl"],
        "answer": "Bat",
    },
    {
        "category": "Trivia",
        "question": "What year did the Titanic sink?",
        "choices": ["1905", "1912", "1920", "1898"],
        "answer": "1912",
    },
    {
        "category": "Trivia",
        "question": "What is the tallest mountain in the world?",
        "choices": ["K2", "Mount Kilimanjaro", "Mount Everest", "Mount Fuji"],
        "answer": "Mount Everest",
    },
    # ── More Speed Round ──
    {
        "category": "Speed Round",
        "question": "Quick! Which of these numbers is odd?",
        "choices": ["14", "22", "37", "48"],
        "answer": "37",
    },
    {
        "category": "Speed Round",
        "question": "Which direction does the sun rise from?",
        "choices": ["North", "South", "East", "West"],
        "answer": "East",
    },
    {
        "category": "Speed Round",
        "question": "How many vowels are in the word 'EDUCATION'?",
        "choices": ["3", "4", "5", "6"],
        "answer": "5",
    },
    {
        "category": "Speed Round",
        "question": "Which is the smallest: millimeter, centimeter, meter, or kilometer?",
        "choices": ["Centimeter", "Millimeter", "Meter", "Kilometer"],
        "answer": "Millimeter",
    },
    {
        "category": "Speed Round",
        "question": "How many zeros are in one million?",
        "choices": ["5", "6", "7", "8"],
        "answer": "6",
    },
    {
        "category": "Speed Round",
        "question": "Quick! What is half of 250?",
        "choices": ["100", "120", "125", "150"],
        "answer": "125",
    },
    # ── More Minecraft ──
    {
        "category": "Minecraft",
        "question": "What food do you use to breed wolves in Minecraft?",
        "choices": ["Steak", "Bones", "Any meat", "Apples"],
        "answer": "Any meat",
    },
    {
        "category": "Minecraft",
        "question": "What is the rarest ore in vanilla Minecraft?",
        "choices": ["Diamond", "Emerald", "Ancient Debris", "Lapis Lazuli"],
        "answer": "Emerald",
    },
    {
        "category": "Minecraft",
        "question": "How many blocks of iron do you need to build an iron golem?",
        "choices": ["3", "4", "5", "6"],
        "answer": "4",
    },
    {
        "category": "Minecraft",
        "question": "What do you need to craft a cake in Minecraft?",
        "choices": ["Eggs, sugar, wheat, milk", "Eggs, cocoa, wheat", "Sugar, wheat, apples", "Milk, sugar, pumpkin"],
        "answer": "Eggs, sugar, wheat, milk",
    },
    {
        "category": "Minecraft",
        "question": "What happens when lightning strikes a pig in Minecraft?",
        "choices": ["It dies", "It becomes a Zombified Piglin", "Nothing", "It catches fire"],
        "answer": "It becomes a Zombified Piglin",
    },
    {
        "category": "Minecraft",
        "question": "What enchantment lets you walk on water by turning it to ice?",
        "choices": ["Aqua Affinity", "Depth Strider", "Frost Walker", "Water Walking"],
        "answer": "Frost Walker",
    },
    # ── More Roblox ──
    {
        "category": "Roblox",
        "question": "What is the name of the default Roblox character?",
        "choices": ["Builderman", "Noob", "Bacon Hair", "Pal"],
        "answer": "Noob",
    },
    {
        "category": "Roblox",
        "question": "Which popular Roblox game has players adopt and raise virtual pets?",
        "choices": ["Brookhaven", "Adopt Me", "MeepCity", "Bloxburg"],
        "answer": "Adopt Me",
    },
    {
        "category": "Roblox",
        "question": "In Roblox, what is a 'Gamepass'?",
        "choices": ["A free trial", "A purchasable in-game perk", "A cheat code", "A type of badge"],
        "answer": "A purchasable in-game perk",
    },
    {
        "category": "Roblox",
        "question": "Which Roblox game is a life simulation set in a neighborhood?",
        "choices": ["Jailbreak", "Bloxburg", "Tower of Hell", "Natural Disaster Survival"],
        "answer": "Bloxburg",
    },
    {
        "category": "Roblox",
        "question": "What Roblox game requires you to climb an increasingly difficult tower with no checkpoints?",
        "choices": ["Tower of Hell", "Obby King", "Mega Tower", "Climb the Stairs"],
        "answer": "Tower of Hell",
    },
    {
        "category": "Roblox",
        "question": "In Roblox Jailbreak, what are the two teams you can choose when joining?",
        "choices": ["Cops and Robbers", "Prisoner and Police", "Heroes and Villains", "Guards and Inmates"],
        "answer": "Prisoner and Police",
    },
    # ── More Picture Round ──
    {
        "category": "Picture Round",
        "question": "What animal is this?",
        "image": {"type": "emoji", "content": "\U0001F427"},
        "choices": ["Puffin", "Penguin", "Seagull", "Pelican"],
        "answer": "Penguin",
    },
    {
        "category": "Picture Round",
        "question": "What is this food?",
        "image": {"type": "emoji", "content": "\U0001F355"},
        "choices": ["Pie", "Pizza", "Flatbread", "Quesadilla"],
        "answer": "Pizza",
    },
    {
        "category": "Picture Round",
        "question": "What sport uses this?",
        "image": {"type": "emoji", "content": "\U0001F3C8"},
        "choices": ["Rugby", "American Football", "Soccer", "Cricket"],
        "answer": "American Football",
    },
    {
        "category": "Picture Round",
        "question": "What animal is this?",
        "image": {"type": "emoji", "content": "\U0001F989"},
        "choices": ["Eagle", "Hawk", "Owl", "Falcon"],
        "answer": "Owl",
    },
    {
        "category": "Picture Round",
        "question": "What is this?",
        "image": {"type": "emoji", "content": "\U0001F30B"},
        "choices": ["Mountain", "Volcano", "Island", "Geyser"],
        "answer": "Volcano",
    },
    {
        "category": "Picture Round",
        "question": "What animal is this?",
        "image": {"type": "emoji", "content": "\U0001F40A"},
        "choices": ["Alligator", "Lizard", "Crocodile", "Komodo Dragon"],
        "answer": "Crocodile",
    },
    {
        "category": "Picture Round",
        "question": "What instrument is this?",
        "image": {"type": "emoji", "content": "\U0001F3B8"},
        "choices": ["Ukulele", "Banjo", "Guitar", "Bass"],
        "answer": "Guitar",
    },
    {
        "category": "Picture Round",
        "question": "Which country does this flag belong to?",
        "image": {"type": "url", "src": "https://flagcdn.com/w320/kr.png", "alt": "A country flag"},
        "choices": ["Japan", "North Korea", "South Korea", "Taiwan"],
        "answer": "South Korea",
    },
    {
        "category": "Picture Round",
        "question": "Which country does this flag belong to?",
        "image": {"type": "url", "src": "https://flagcdn.com/w320/it.png", "alt": "A country flag"},
        "choices": ["Ireland", "Italy", "Mexico", "Hungary"],
        "answer": "Italy",
    },
]
